const characterObject = {
  id: "",
  userId: "",
  imageURL: "",
  firstname: "",
  lastname: "",
  classes: [],
  level: "",
  background: "",
  playername: "",
  race: "",
  alignment: "",
  xp: "",
  armorclass: "",
  initiative: "",
  speed: "",
  hitdice: "",
  hitpoints: "",
  temphp: "",
  mods: [
    { name: "Strength", shortName: "str", value: "", prof: false },
    { name: "Dexterity", shortName: "dex", value: "", prof: false },
    { name: "Constitution", shortName: "con", value: "", prof: false },
    { name: "Intelligence", shortName: "int", value: "", prof: false },
    { name: "Wisdom", shortName: "wis", value: "", prof: false },
    { name: "Charisma", shortName: "char", value: "", prof: false },
  ],
  characterInfo: [
    { name: "Traits", content: "" },
    { name: "Values", content: "" },
    { name: "Flaws", content: "" },
    { name: "Ideals", content: "" },
  ],
  attacks: [
    {
      name: "Unarmed Strike",
      bonus: "+3",
      damage: "2 Kinetic",
    },
    {
      name: "",
      bonus: "",
      damage: "",
    },
    {
      name: "",
      bonus: "",
      damage: "",
    },
  ],
  equipment: [
    {
      name: "Knife",
      quantity: 1,
      category: "Equipment",
      equipped: false,
      description: "",
    },
    {
      name: "",
      quantity: "",
      category: "",
      equipped: false,
      description: "",
    },
    {
      name: "",
      quantity: "",
      category: "",
      equipped: false,
      description: "",
    },
  ],
  languages: ["", ""],
  notes: "",
};

export default characterObject;
