const characterObject = {
  id: "",
  userId: "",
  imageURL: "",
  firstname: "",
  lastname: "",
  classes: [],
  level: "",
  background: "",
  playername: "",
  race: "",
  alignment: "",
  xp: "",
  armorclass: "",
  initiative: "",
  speed: "",
  hitdice: "",
  hitpoints: "",
  temphp: "",
  mods: [
    { name: "Strength", shortName: "str", value: "", prof: false },
    { name: "Dexterity", shortName: "dex", value: "", prof: false },
    { name: "Constitution", shortName: "con", value: "", prof: false },
    { name: "Intelligence", shortName: "int", value: "", prof: false },
    { name: "Wisdom", shortName: "wis", value: "", prof: false },
    { name: "Charisma", shortName: "char", value: "", prof: false },
  ],
  characterInfo: [
    { name: "Traits", content: "" },
    { name: "Values", content: "" },
    { name: "Flaws", content: "" },
    { name: "Ideals", content: "" },
  ],
};

export default characterObject;
